src/tools/ui: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    src/tools/ui.c: In function 'ui_draw_footer_button':
    src/tools/ui.c:329:9: error: format not a string literal and no format arguments [-Werror=format-security]
      329 |         wprintw(ui->win_footer->win, key);
          |         ^~~~~~~

Let's wrap all the missing places with "%s" format.